#!/usr/bin/env python3
import string
import time
import platform
import signal
import sys
from datetime import datetime

VERSION = "3.0"
RUNNING = False


def banner():
    os.system("cls" if os.name == "nt" else "clear")
    print(f"""
\033[96m
███╗   ███╗██╗   ██╗███╗   ██╗███╗   ██╗ █████╗
████╗ ████║██║   ██║████╗  ██║████╗  ██║██╔══██╗
██╔████╔██║██║   ██║██╔██╗ ██║██╔██╗ ██║███████║
██║╚██╔╝██║██║   ██║██║╚██╗██║██║╚██╗██║██╔══██║
██║ ╚═╝ ██║╚██████╔╝██║ ╚████║██║ ╚████║██║  ██║
╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═══╝╚═╝  ╚═╝

              🚀 MunnaTheDev Project 🚀 stop workking bc of leak
═══════════════════════════════════════════════
 Author       : MunnaTheDev
 Version      : {VERSION}
 Python       : {platform.python_version()}
 System       : {platform.system()} {platform.release()}
 Machine      : {platform.machine()}
═══════════════════════════════════════════════
\033[0m
""")
